import { expect, test } from '@playwright/test'
import { expectNoAxeViolations, open, startTimer, timeText } from './helpers'

test('B1 activo el temporizador sin el chat', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: 'Temporizador' }).click()
  await expectNoAxeViolations(page)
  await page.getByRole('button', { name: '15 min' }).click()
  await page.getByLabel('Título (opcional)').fill('Leer el informe')
  await page.getByRole('button', { name: 'Play' }).click()
  await expect(page.getByRole('heading', { name: 'Leer el informe' })).toBeVisible()
  await expect(timeText(page)).toHaveText('15:00')
  await expectNoAxeViolations(page)
})

test('B1 sin título se llama «Sin título» y acepta otros minutos', async ({ page }) => {
  await open(page)
  await startTimer(page, 7)
  await expect(page.getByRole('heading', { name: 'Sin título' })).toBeVisible()
  await expect(timeText(page)).toHaveText('07:00')
})

test('B2 veo la cuenta atrás y sigue correcta al recargar', async ({ page }) => {
  await open(page)
  await startTimer(page, 25, 'Escribir')
  await expect(timeText(page)).toHaveText('25:00')
  await page.clock.runFor(1000)
  await expect(timeText(page)).toHaveText('24:59')
  await page.clock.runFor(60_000)
  await expect(timeText(page)).toHaveText('23:59')
  await page.reload()
  await expect(timeText(page)).toHaveText('23:59')
  await page.clock.runFor(60_000)
  await expect(timeText(page)).toHaveText('22:59')
})

test('B3 pauso y reanudo', async ({ page }) => {
  await open(page)
  await startTimer(page, 10)
  await page.clock.runFor(60_000)
  await page.getByRole('button', { name: 'Pausar' }).click()
  await expect(timeText(page)).toHaveText('09:00')
  await page.clock.runFor(5 * 60_000)
  await expect(timeText(page)).toHaveText('09:00')
  await page.getByRole('button', { name: 'Reanudar' }).click()
  await page.clock.runFor(60_000)
  await expect(timeText(page)).toHaveText('08:00')
})

test('B5 termino el bloque con confirmación y los minutos quedan guardados', async ({ page }) => {
  await open(page)
  await startTimer(page, 25, 'Diseñar')
  await page.clock.runFor(10 * 60_000)
  await page.getByRole('button', { name: 'Terminar' }).click()
  const dialog = page.getByRole('dialog', { name: '¿Terminar este bloque?' })
  await expect(dialog).toBeVisible()
  await expectNoAxeViolations(page)
  await dialog.getByRole('button', { name: 'Seguir' }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: 'Terminar' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Terminar' }).click()
  await expect(page.getByLabel('¿Qué necesitas hacer hoy?')).toBeVisible()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('presencia:v1') ?? '{}'))
  expect(saved.records).toHaveLength(1)
  expect(saved.records[0]).toMatchObject({ kind: 'focus', title: 'Diseñar' })
  // Diez minutos trabajados (más el segundo que corre el reloj mientras axe revisa el diálogo).
  expect(Math.round(saved.records[0].focusMs / 60_000)).toBe(10)
})

test('B7 con un bloque en marcha no se puede empezar otro', async ({ page }) => {
  await open(page)
  await startTimer(page, 25)
  await page.getByRole('button', { name: 'Hoy' }).click()
  await expect(page.getByRole('button', { name: 'Temporizador' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Respirar', exact: true })).toBeDisabled()
  await expect(page.getByText('Ya hay un bloque en marcha')).toBeVisible()
  await page.getByRole('button', { name: 'Ir al bloque' }).click()
  await expect(timeText(page)).toBeVisible()
})

test('B8 vuelvo a Hoy sin terminar y la franja me devuelve al bloque', async ({ page }) => {
  await open(page)
  await startTimer(page, 25, 'Revisar correos')
  await page.clock.runFor(60_000)
  await page.getByRole('button', { name: 'Hoy' }).click()
  const franja = page.getByRole('button', { name: /Revisar correos, quedan \d\d:\d\d/ })
  await expect(franja).toBeVisible()
  await expect(franja).toContainText('24:00')
  await expectNoAxeViolations(page)
  await franja.click()
  await expect(page.getByRole('heading', { name: 'Revisar correos' })).toBeVisible()
})

test('B9 veo el tiempo en la pestaña', async ({ page }) => {
  await open(page)
  await startTimer(page, 25)
  await page.clock.runFor(1000)
  await expect(page).toHaveTitle('24:59 · Presencia')
  await page.getByRole('button', { name: 'Pausar' }).click()
  await expect(page).toHaveTitle('Presencia')
})

test('B10 Espacio pausa y reanuda, y Escape cierra el diálogo', async ({ page }) => {
  await open(page)
  await startTimer(page, 25)
  await page.locator('body').click({ position: { x: 5, y: 400 } })
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Reanudar' })).toBeVisible()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Pausar' })).toBeVisible()
  await page.getByRole('button', { name: 'Terminar' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(timeText(page)).toBeVisible()
})

test('B11 el tiempo se anuncia cada minuto y al terminar, no cada segundo', async ({ page }) => {
  await open(page)
  await startTimer(page, 2)
  const live = page.locator('[aria-live="polite"]')
  await expect(live).toHaveText('Quedan 2 minutos')
  await page.clock.runFor(20_000)
  await expect(live).toHaveText('Quedan 2 minutos')
  await page.clock.runFor(41_000)
  await expect(live).toHaveText('Queda 1 minuto')
  await page.clock.runFor(60_000)
  await expect(live).toHaveText('Tiempo terminado')
})
